public class DataTypeDemo {
	
    public void methodDemo(){
        
    /*List<String> strList=new List<String>();
        strList.add('A');
        strList.add('B');
	System.debug('OutPut List'+strList);
 =====================================================     */
        
       // List<Account> accList=[SELECT Id,Name FROM Account LIMIT 2];
        //System.debug('accList='+accList);
        
   /*     Map<String,String> demoMap=new Map<String,String>();
        demoMap.put('1','FirstStep');
        demoMap.put('2','SecondStep');
    System.debug('This Is Map Example'+demoMap);
    ---------------------------------------------------------*/
       /*
        List<String> strList=new List<String>(); 	//List 1
        List<String> strList2=new List<String>();		// List 2
     	Set<String> strSet=new Set<String>();		//Set
        
        strList.add('s');
        strList.add('a');
        strList.add(1,'O');
        
		strList2.add('Aust');
        strList2.addAll(strList);
        
        strSet.add('Japan');
        strList2.addAll(strSet);
        //System.debug('strList2 :'+strList2);    //Set Values add To List 
        //System.debug('List Add Is :'+strList);
        //System.debug('List 2 Is:'+strList2);
    	//strList2.clear();			// Clear Used
        //System.debug('After Clear:'+strList2);  
	 
       // System.debug('Get method Using :'+strList.get(2));  // Used get
      
-------------------------------------------------------------------
         */
      	
        /*
	//-------------------SObject Used -------------
		List<Account> accList=new List<Account>();
        accList=[SELECT Id,Name FROM Account LIMIT 3];
        System.debug('This Is Account List :'+accList);
        
        */
        
        //-------------------List Complete-----------------------
       
        
        //--------- SET Start---------------------
        
        
        
}
    }